version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"

volumes:
  db_data:
